# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build darwin amd64
      run: env GOOS=darwin GOARCH=amd64 go build -ldflags="-w" -trimpath -o build/todo-darwin-amd64 .
    - name: Build darwin arm64
      run: env GOOS=darwin GOARCH=arm64 go build -ldflags="-w" -trimpath -o build/todo-darwin-arm64 .
    - name: Build linux amd64
      run: env GOOS=linux GOARCH=amd64 go build -ldflags="-w" -trimpath -o build/todo-linux-amd64 .
    - name: Build linux arm64
      run: env GOOS=linux GOARCH=arm64 go build -ldflags="-w" -trimpath -o build/todo-linux-arm64 .
    - name: Build windows amd64
      run: env GOOS=windows GOARCH=amd64 go build -ldflags="-w" -trimpath -o build/todo-windows-amd64.exe .
    - name: Build windows arm64
      run: env GOOS=windows GOARCH=arm64 go build -ldflags="-w" -trimpath -o build/todo-windows-arm64.exe .

    - name: Check build folder
      run:  ls build/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/todo-darwin-amd64
          build/todo-darwin-arm64
          build/todo-linux-amd64
          build/todo-linux-arm64
          build/todo-windows-amd64.exe
          build/todo-windows-arm64.exe
